# Generated by Django 4.0.3 on 2022-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_checkoutcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='delivery',
            field=models.CharField(default='P', max_length=20),
        ),
    ]
